# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/OP4C7D/setup-makefiles.sh

# Connectivity / Wi-Fi & Bluetooth
BOARD_WLAN_DEVICE := mtk
BOARD_CONNECTIVITY_VENDOR_3GDATA_LIMIT := true
BOARD_USES_MTK_AUDIO := true

# GPS
BOARD_GPS_LAL_LANDSCAPE := true

# Graphics / Rendering HAL switches
BOARD_USES_METADATA_DYNAMIC_BUFFER := true
USE_OPENGL_RENDERER := true

# Radio / Telephony Configurations (MediaTek RILD)
MTK_NUM_SIM_SUPPORT := 2
MTK_RILD_TEXT_CLONE := true

# Security / Crypto
SIM_COUNT := 2
BOARD_USES_QCOM_HARDWARE := false
